### ISSUE TITLE
No way to runserver with current setup

### ISSUE THREAD

**Issue by joseph-holms** [KerkhoffTechnologies/django-autotask#24]
I am trying to use this, but there is no option to do a local runserver. Is there anything special that needs to be run? Thanks.

**Comment by kti-matt** [comment]
There are no instructions for running a local server with this project because it's a library and the expectation is that you'll integrate it into your own project where you already have patterns for running the server.

django-autotask doesn't do anything useful on its own.

**Comment by joseph-holms** [comment]
> There are no instructions for running a local server with this project because it's a library and the expectation is that you'll integrate it into your own project where you already have patterns for running the server.
> 
> django-autotask doesn't do anything useful on its own.

Awesome, just wanted to make sure of that. Great project by the way.
